name: Build with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Python and pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install nuitka
        pip3 install requests
    - name: Build with Nuitka
      run: |
        python3 -m nuitka --standalone --onefile --output-dir=dist main.py
        mv ./dist/main.bin ./OProxy
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: OProxy
        path: OProxy